In [ ]:
%matplotlib notebook

In [9]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import csv
import os
import numpy
import requests as rq
import pandas as pd
from io import BytesIO
import json

In [10]:
csv_path = os.path.join('Resources/WDI_trimmed_all.csv')
with open(csv_path) as csvfile:
    trimmed_df = csv.reader(csvfile, delimiter=",")
    trimmed_df = pd.DataFrame(trimmed_df))

In [11]:
trimmed_df

,0,1,2,3,4,5,6,7,8
0,Country Name,Country Code,Series Name,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019]
1,Argentina,ARG,Adjusted net national income (annual % growth),-3.446138435,5.050909519,-1.782622202,5.672500021,-6.949254354,-4.698899588
2,Argentina,ARG,Adjusted net national income (constant 2015 US$),4.79448E+11,5.03664E+11,4.94686E+11,5.22747E+11,4.8642E+11,4.63564E+11
3,Argentina,ARG,Adjusted net national income (current US$),4.35775E+11,5.03664E+11,4.70935E+11,5.5046E+11,4.30565E+11,3.66726E+11
4,Argentina,ARG,Adjusted net national income per capita (annua...,-4.501896117,3.924541342,-2.815488968,4.58219842,-7.889687014,-5.640931522
...,...,...,...,...,...,...,...,...,...
1316,Vietnam,VNM,"Unemployment, total (% of total labor force) (...",1.26,1.85,1.85,1.87,1.16,2.04
1317,Vietnam,VNM,"Unemployment, youth female (% of female labor ...",4.64,6.39,6.67,6.96,4.34,6.71
1318,Vietnam,VNM,"Unemployment, youth male (% of male labor forc...",4.59,6.13,6.72,7,4.7,6.59
1319,Vietnam,VNM,"Unemployment, youth total (% of total labor fo...",4.61,6.25,6.69,6.98,4.54,6.64
1320,Vietnam,VNM,Women Business and the Law Index Score (scale ...,76.25,76.25,78.75,78.75,78.75,78.75